set-option -g prefix None
set-option -g prefix2 None
set-option -g status off
set-option -g exit-empty off
set-option -g exit-unattached off
set-option -g destroy-unattached off
set-option -g default-terminal "tmux-256color"
set-option -g history-limit 50000
set-option -g focus-events on
set-option -g set-clipboard on
set-option -g mouse on
bind-key -T root PPage copy-mode -eu
bind-key -T root Home copy-mode \; send-keys -X history-top
bind-key -T copy-mode Home send-keys -X history-top
bind-key -T copy-mode NPage send-keys -X page-down-and-cancel
bind-key -T copy-mode End send-keys -X cancel
bind-key -T copy-mode-vi Home send-keys -X history-top
bind-key -T copy-mode-vi NPage send-keys -X page-down-and-cancel
bind-key -T copy-mode-vi End send-keys -X cancel
set-option -g allow-passthrough on
set-option -g extended-keys on
set-option -g extended-keys-format csi-u
set-option -ag terminal-features ",xterm-256color:RGB:extkeys"
set-window-option -g remain-on-exit off
set-window-option -g aggressive-resize on
